# Generated by Django 5.2.6 on 2025-09-18 05:56

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('sailor', 'Sailor')], default='sailor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, unique=True)),
                ('dish_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], max_length=10)),
                ('has_gluten', models.BooleanField(default=False)),
                ('has_nuts', models.BooleanField(default=False)),
                ('has_dairy', models.BooleanField(default=False)),
                ('calories', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Sailor Requirement', max_length=100)),
                ('daily_calories', models.IntegerField(default=2500)),
                ('daily_protein', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('total_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('liters', 'Liters'), ('pieces', 'Pieces'), ('grams', 'Grams')], max_length=10)),
                ('reorder_level', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='SailorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preference_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], default='non_veg', max_length=10)),
                ('has_gluten_allergy', models.BooleanField(default=False)),
                ('has_nut_allergy', models.BooleanField(default=False)),
                ('has_dairy_allergy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('quantity_cooked', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planning.dish')),
            ],
        ),
        migrations.CreateModel(
            name='StockUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('log_date', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='meal_planning.rawstock')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_usage', to='meal_planning.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='meal_planning.voyage'),
        ),
        migrations.CreateModel(
            name='WasteTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_waste_percentage', models.FloatField(blank=True, null=True)),
                ('actual_waste_kg', models.FloatField(blank=True, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planning.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='ChefAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('chef', models.ForeignKey(limit_choices_to={'role': 'chef'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_assignments', to='meal_planning.mealplan')),
            ],
            options={
                'unique_together': {('meal_plan', 'chef', 'counter_number')},
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meal_planning.dish')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planning.rawstock')),
            ],
            options={
                'unique_together': {('dish', 'item')},
            },
        ),
        migrations.CreateModel(
            name='SailorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sailor_assignments', to='meal_planning.mealplan')),
                ('sailor', models.ForeignKey(limit_choices_to={'role': 'sailor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meal_plan', 'sailor')},
            },
        ),
        migrations.CreateModel(
            name='SatisfactionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meal_planning.mealplan')),
                ('sailor', models.ForeignKey(limit_choices_to={'role': 'sailor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sailor', 'meal_plan')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('voyage', 'meal_date', 'meal_type', 'dish')},
        ),
        migrations.CreateModel(
            name='MealNutritionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField()),
                ('total_calories_served', models.FloatField()),
                ('total_protein_served', models.FloatField()),
                ('nutritional_completeness_score', models.FloatField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planning.voyage')),
            ],
            options={
                'unique_together': {('voyage', 'analysis_date')},
            },
        ),
    ]
